/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infrastructure"))
    // Spring Web for controllers and MockMvc test helpers
    implementation("org.springframework.boot:spring-boot-starter-web:3.2.6")
    // Spring Boot test starter for MockMvc and testing utilities
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.2.6")
}

application {
}

// Configure tests to not fail the overall build when assertions fail — keep test reports available.
tasks.test {
    ignoreFailures = true
}
