/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    // Assertions library for richer fluent assertions in tests
    testImplementation("org.assertj:assertj-core:3.24.2")
}
